### ISSUE TITLE
Altered TBProfiler database db_version doesn't contain "commit" key

### ISSUE THREAD

**Issue by ryanjameskennedy** [Clinical-Genomics-Lund/bonsai-prp#20]
The following error occured when running TBProfiler with the altered database:
```
Traceback (most recent call last):
    File "/usr/local/bin/prp", line 8, in <module>
      sys.exit(cli())
               ^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/bonsai-prp/prp/cli.py", line 232, in create_bonsai_input
      version=pred_res["db_version"]["commit"],
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  KeyError: 'commit'
  ```

**Comment by ryanjameskennedy** [comment]
Structural question here, so when we run TBProfiler with our self made tbdb, the "commit" field is obviously not created for `db_version` (see below example): 
```
    "db_version": {
        "name": "who",
        "Date": "2023-12-22 13:55:18.644727",
        "Author": "NA"
    },
```
So I want to combine `db_version["name"] + "_" + reformat_date_str(db_version["Date"])`. Though I can easily achieve this by adding the following to [cli.py line 228](https://github.com/Clinical-Genomics-Lund/bonsai-prp/blob/6215c85ac8c78a188ffa69c9597a66dd77edd37b/prp/cli.py#L228):
```
        db_version = pred_res["db_version"]
        input_date = db_version["Date"]
        exp_format = "%a %b %d %H:%M:%S %Y %z"
        formatted_date = datetime.strptime(input_date, exp_format).strftime("%d%m%y")
        backup_version = db_version["name"] + "_" + formatted_date
        version = db_version["commit"] if "commit" in db_version else backup_version
```
Is this fine or do you want me to add this as a function to `utils.py` and move `utils.py` to a more accessible part of the prp file structure? @mhkc
