### ISSUE TITLE
Pysam error when trying to read the bam file 

### ISSUE THREAD

**Issue by ryanjameskennedy** [Clinical-Genomics-Lund/bonsai-prp#59]
The following error occurs regarding oppening the bam file:
```
  [W::hts_idx_load3] The index file is older than the data file: /fs1/results_dev/jasen/mtuberculosis/bam/11TB0101651.bam.bai
  [E::bgzf_read_block] Invalid BGZF header at offset 564
  [E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
  Traceback (most recent call last):
    File "/usr/local/bin/prp", line 8, in <module>
      sys.exit(cli())
               ^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 101, in augment_usage_errors
      yield
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/prp/cli.py", line 301, in create_bonsai_input
      bam_ref_genome = get_reference_seq_accnr(bam)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/prp/parse/mapping.py", line 17, in get_reference_seq_accnr
      read = next(samfile.fetch())
             ^^^^^^^^^^^^^^^^^^^^^
  StopIteration
  OSError: [Errno 0] Success
  Exception ignored in: 'pysam.libcalignmentfile.AlignmentFile.__dealloc__'
  OSError: [Errno 0] Success
  ```

**Comment by ryanjameskennedy** [comment]
This was an error whereby two JASEN processess were writing bam files to the same directory. Problem solved by this [PR](https://github.com/genomic-medicine-sweden/jasen/pull/317).
